version: "3"

services:
  auctionserver:
    build: ./AuctionBiddingServer
    ports:
      - "8080:8080"
    restart: unless-stopped

  bidder1:
    build: ./BiddingClient
    command: java -jar BidClient.jar --delay=10 --port=8000 --name=tim
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - auctionserver
    environment:
      - SERVER_URL_PREFIX=http://auctionserver:8080
      - BIDDER_URL_PREFIX=http://bidder1

  bidder2:
    build: ./BiddingClient
    command: java -jar BidClient.jar --delay=100 --port=8001 --name=tim1
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      - auctionserver
    environment:
      - SERVER_URL_PREFIX=http://auctionserver:8080
      - BIDDER_URL_PREFIX=http://bidder2


  bidder3:
    build: ./BiddingClient
    command: java -jar BidClient.jar --delay=150 --port=8001 --name=tim1
    ports:
      - "8002:8002"
    restart: unless-stopped
    depends_on:
      - auctionserver
    environment:
      - SERVER_URL_PREFIX=http://auctionserver:8080
      - BIDDER_URL_PREFIX=http://bidder3
